export const FALLBACK_BARANGAYS = [
  { slug: 'bantayan', name: 'Bantayan' },
  { slug: 'barangay-1', name: 'Barangay 1' },
  { slug: 'barangay-2', name: 'Barangay 2' },
  { slug: 'barangay-3', name: 'Barangay 3' },
  { slug: 'barangay-4', name: 'Barangay 4' },
  { slug: 'barangay-5', name: 'Barangay 5' },
  { slug: 'barangay-6', name: 'Barangay 6' },
  { slug: 'barangay-7', name: 'Barangay 7' },
  { slug: 'barangay-8', name: 'Barangay 8' },
  { slug: 'barangay-9', name: 'Barangay 9' },
  { slug: 'binicuil', name: 'Binicuil' },
  { slug: 'camansi', name: 'Camansi' },
  { slug: 'camingawa', name: 'Camingawa' },
  { slug: 'camugao', name: 'Camugao' },
  { slug: 'carol-an', name: 'Carol-an' },
  { slug: 'daan-banua', name: 'Daan Banua' },
  { slug: 'hilamonan', name: 'Hilamonan' },
  { slug: 'inapoy', name: 'Inapoy' },
  { slug: 'linao', name: 'Linao' },
  { slug: 'locotan', name: 'Locotan' },
  { slug: 'magballo', name: 'Magballo' },
  { slug: 'oringao', name: 'Oringao' },
  { slug: 'orong', name: 'Orong' },
  { slug: 'pinaguinpinan', name: 'Pinaguinpinan' },
  { slug: 'salong', name: 'Salong' },
  { slug: 'tabugon', name: 'Tabugon' },
  { slug: 'tagoc', name: 'Tagoc' },
  { slug: 'tagukon', name: 'Tagukon' },
  { slug: 'talubangi', name: 'Talubangi' },
  { slug: 'tampalon', name: 'Tampalon' },
  { slug: 'tan-awan', name: 'Tan-awan' },
  { slug: 'tapi', name: 'Tapi' },
];